/* tslint:disable */
/* eslint-disable */
/**
 * AI Terraform Module Generator
 * Generate Terraform modules using AI with Terraform Registry Protocol support
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ListVersions200ResponseModulesInnerVersionsInner,
    ListVersions200ResponseModulesInnerVersionsInnerFromJSON,
    ListVersions200ResponseModulesInnerVersionsInnerToJSON,
} from './ListVersions200ResponseModulesInnerVersionsInner';

/**
 * 
 * @export
 * @interface ListVersions200ResponseModulesInner
 */
export interface ListVersions200ResponseModulesInner {
    /**
     * 
     * @type {Array<ListVersions200ResponseModulesInnerVersionsInner>}
     * @memberof ListVersions200ResponseModulesInner
     */
    versions?: Array<ListVersions200ResponseModulesInnerVersionsInner>;
    /**
     * 
     * @type {string}
     * @memberof ListVersions200ResponseModulesInner
     */
    source?: string;
}

/**
 * Check if a given object implements the ListVersions200ResponseModulesInner interface.
 */
export function instanceOfListVersions200ResponseModulesInner(obj: object): obj is ListVersions200ResponseModulesInner {
    let validKeys = ['versions', 'source'];
    return Object.keys(obj).every(key => validKeys.includes(key));
}

export function ListVersions200ResponseModulesInnerFromJSON(json: any): ListVersions200ResponseModulesInner {
    return ListVersions200ResponseModulesInnerFromJSONTyped(json);
}

export function ListVersions200ResponseModulesInnerFromJSONTyped(json: any): ListVersions200ResponseModulesInner {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        'versions': !json['versions'] ? undefined : ((json['versions'] as Array<any>).map(ListVersions200ResponseModulesInnerVersionsInnerFromJSON)),
        'source': !json['source'] ? undefined : json['source'],
    };
}

export function ListVersions200ResponseModulesInnerToJSON(value?: ListVersions200ResponseModulesInner | null): any {
    return ListVersions200ResponseModulesInnerToJSONTyped(value);
}

export function ListVersions200ResponseModulesInnerToJSONTyped(value?: ListVersions200ResponseModulesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'versions': value.versions === undefined ? undefined : ((value.versions as Array<any>).map(ListVersions200ResponseModulesInnerVersionsInnerToJSON)),
        'source': value.source,
    };
}

