/* tslint:disable */
/* eslint-disable */
/**
 * AI Terraform Module Generator
 * Generate Terraform modules using AI with Terraform Registry Protocol support
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListVersions200ResponseModulesInner } from './ListVersions200ResponseModulesInner';
import {
    ListVersions200ResponseModulesInnerFromJSON,
    ListVersions200ResponseModulesInnerToJSON,
} from './ListVersions200ResponseModulesInner';

/**
 * 
 * @export
 * @interface ListVersions200Response
 */
export interface ListVersions200Response {
    /**
     * 
     * @type {Array<ListVersions200ResponseModulesInner>}
     * @memberof ListVersions200Response
     */
    modules?: Array<ListVersions200ResponseModulesInner>;
}

/**
 * Check if a given object implements the ListVersions200Response interface.
 */
export function instanceOfListVersions200Response(value: object): value is ListVersions200Response {
    let validKeys = ['modules'];
    return Object.keys(value).every(key => validKeys.includes(key));
}

export function ListVersions200ResponseFromJSON(json: any): ListVersions200Response {
    return ListVersions200ResponseFromJSONTyped(json);
}

export function ListVersions200ResponseFromJSONTyped(json: any): ListVersions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'modules': json['modules'] == null ? undefined : ((json['modules'] as Array<any>).map(ListVersions200ResponseModulesInnerFromJSON)),
    };
}

export function ListVersions200ResponseToJSON(json: any): ListVersions200Response {
    return ListVersions200ResponseToJSONTyped(json);
}

export function ListVersions200ResponseToJSONTyped(value?: ListVersions200Response | null): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modules': value['modules'] == null ? undefined : ((value['modules'] as Array<any>).map(ListVersions200ResponseModulesInnerToJSON)),
    };
}

